name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'

jobs:
  msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        qt: [qt5, qt6]
        msystem: [mingw64, clang64]

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          ${{ matrix.qt }}-base:p
          ${{ matrix.qt }}-tools:p

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive

    - name: Build
      shell: msys2 {0}
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -B build .
        cmake --build build --parallel $(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-${{ matrix.msystem }}-${{ matrix.qt }}
        path: FreePictureSplitter/build/bin
        
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt: [qt5, qt6]
        
    steps:
    - name: Install dependencies
      if: matrix.qt == 'qt5'
      run: |
        sudo apt update
        sudo apt install -y build-essential qtbase5-dev qttools5-dev-tools qttools5-dev libxkbcommon-dev

    - name: Install dependencies
      if: matrix.qt == 'qt6'
      run: |
        sudo apt update
        sudo apt install -y build-essential qt6-base-dev linguist-qt6 qt6-tools-dev libxkbcommon-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive

    - name: Build
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -B build .
        cmake --build build --parallel $(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-ubuntu-${{ matrix.qt }}
        path: FreePictureSplitter/build/bin
