name: Test Build

on:
  workflow_dispatch:
  push:
    branches:
      - 3.x
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'
      - 'config/**'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - 3.x
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'
      - 'config/**'
      - '.github/workflows/*.yml'

jobs:
  msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        qt: [qt5, qt6]
        msystem: [mingw64, clang64]

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          ${{ matrix.qt }}-base:p
          ${{ matrix.qt }}-tools:p
          ${{ matrix.qt }}-translations:p
          ${{ matrix.qt }}-imageformats:p

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive
        fetch-depth: 1
        ref: 3.x

    - name: Build
      shell: msys2 {0}
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_BUILD_TYPE=Release -B build .
        cmake --build build -j
        cmake --install build
        
  msvc:
    # We only support Qt6 when building using MSVC.
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        arch: win64_msvc2022_64
        install-deps: true
        modules: "qtimageformats"
        setup-python: false
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive
        fetch-depth: 1
        ref: 3.x
      
    - name: Build
      shell: pwsh
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -B build .
        cmake --build build -j --config Release
        cmake --install build
      
  ubuntu:
    # We only support Qt6 on Linux.
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        arch: linux_gcc_64
        install-deps: true
        modules: "qtimageformats"
        setup-python: false

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive
        fetch-depth: 1
        ref: 3.x

    - name: Build
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_BUILD_TYPE=Release -B build .
        cmake --build build -j
        cmake --install build
