name: Test Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'
      - 'config/**'
      - '.devcontainer/**'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'
      - 'config/**'
      - '.github/workflows/*.yml'

jobs:
  msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [ucrt64, clang64]

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        location: D:\
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          qt6-base:p
          qt6-tools:p
          qt6-svg:p
          qt6-translations:p

    - name: Checkout
      uses: actions/checkout@v5
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive
        fetch-depth: 1

    - name: Build
      shell: msys2 {0}
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/freepicturesplitter -B build .
        cmake --build build -j
        cmake --install build
        
    - name: Upload Build Output
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-msys2-${{ matrix.msystem }}
        path: D:\msys64\opt\freepicturesplitter
        compression-level: 9
      
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.9.1
        arch: linux_gcc_64
        install-deps: true
        modules: "qtimageformats"
        setup-python: false

    - name: Checkout
      uses: actions/checkout@v5
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive
        fetch-depth: 1

    - name: Build
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/freepicturesplitter -B build .
        cmake --build build -j
        cmake --install build
        
    - name: Upload Build Output
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-ubuntu
        path: /opt/freepicturesplitter
        compression-level: 9
