name: build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        qt-version: [5, 6]
        msystem: [mingw64, clang64]

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          qt${{ matrix.qt-version }}-base:p
          qt${{ matrix.qt-version }}-tools:p

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive

    - name: Build
      shell: msys2 {0}
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -B build .
        cmake --build build --parallel $(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-${{ matrix.msystem }}-qt${{ matrix.qt-version }}
        path: FreePictureSplitter/build/bin
        
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt-version: [5, 6]
        
    steps:
    - name: Install dependencies
      if: matrix.qt-version == 5
      run: |
        sudo apt update
        sudo apt install -y build-essential qtbase5-dev qttools5-dev-tools qttools5-dev libxkbcommon-dev

    - name: Install dependencies
      if: matrix.qt-version == 6
      run: |
        sudo apt update
        sudo apt install -y build-essential qt6-base-dev linguist-qt6 qt6-tools-dev libxkbcommon-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive

    - name: Build
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -B build .
        cmake --build build --parallel $(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-ubuntu-qt${{ matrix.qt-version }}
        path: FreePictureSplitter/build/bin
