name: Test Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.clang-format'
      - 'docs/**'
      - '.github/workflows/*.yml'

jobs:
  msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [mingw64, clang64]

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          qt6-base:p
          qt6-tools:p
          qt6-svg:p
          qt6-translations:p

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive

    - name: Build
      shell: msys2 {0}
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_INSTALL_PREFIX=/opt/freepicturesplitter -B build .
        cmake --build build -j
        cmake --install build
        
  msvc:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.9.*
        arch: win64_msvc2022_64
        install-deps: true
        modules: "qtimageformats"
        setup-python: false
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive
      
    - name: Build
      shell: pwsh
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_INSTALL_PREFIX=D:\FreePictureSplitter -B build .
        cmake --build build -j --config Release
        cmake --install build
      
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.9.*
        arch: linux_gcc_64
        install-deps: true
        modules: "qtimageformats"
        setup-python: false

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive

    - name: Build
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_INSTALL_PREFIX=/opt/freepicturesplitter -B build .
        cmake --build build -j
        cmake --install build
