name: CppCheck

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: zxunge/FreePictureSplitter
          submodules: recursive
          
      - name: Install dpendencies for checking
        run: |
          sudo apt update
          sudo apt install -y build-essential qt6-base-dev linguist-qt6 qt6-tools-dev libxkbcommon-dev cppcheck
          
      - name: Generate build steps and check
        run: |
          mkdir build && cd $_
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cppcheck --project=compile_commands.json --check-library --enable=all --output-file=cppcheck_report.txt --verbose
          
      - name: Print results
        run: cat build/cppcheck_report.txt