name: CppCheck

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: zxunge/FreePictureSplitter
          submodules: recursive
          
      - name: Install dpendencies for checking
        run: |
          sudo apt update
          sudo apt install -y build-essential qt6-base-dev linguist-qt6 qt6-tools-dev libxkbcommon-dev
          
      - name: Generate build steps
        run: |
          mkdir build && cd $_
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      
      - name: CppCheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library: enable
          other_options: --project=build/compile_commands.json
        
      - name: Clean working directory
        run: rm -rf build
        
      - name: Publish Report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'