name: linux-ubuntu

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:

    # WxWidgets
    - name: Install dependencies.
      run: |
        sudo apt-get update
        sudo apt-get install gcc g++ build-essential cmake git libedit-dev libgtk-3-dev libhunspell-dev libsqlite3-dev libssh-dev pkg-config xterm
    
    - name: Checkout WxWidgets
      uses: actions/checkout@v4
      with:
        repository: wxWidgets/wxWidgets
        ref: v3.2.6
        submodules: recursive
        path: wxWidgets

    - name: Build and install wxWidgets
      run: |
        mkdir -p wxWidgets/build-release
        cd wxWidgets/build-release
        ../configure --disable-debug_flag --with-gtk=3 --enable-stl
        make -j$(nproc) && sudo make install

    - name: Checkout FreePictureSplitter
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter

    - name: Build
      shell: bash
      run: |
        cd FreePictureSplitter/
        mkdir build && cd $_
        cmake ..
        cmake --build . --parallel $(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-git
        path: FreePictureSplitter/build/bin
