name: linux-ubuntu

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:

    # WxWidgets
    - name: Install dependencies for wxWidgets, and Clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install build-essential cmake git libedit-dev libgtk-3-dev libhunspell-dev libsqlite3-dev libssh-dev pkg-config xterm
    
    - name: Checkout WxWidgets
      uses: actions/checkout@v4
      with:
        repository: wxWidgets/wxWidgets
        ref: v3.2.6
        submodules: recursive
        path: wxWidgets

    - name: Build and install wxWidgets
      run: |
        mkdir -p wxWidgets/build-release
        cd wxWidgets/build-release
        ../configure --disable-debug_flag --with-gtk=3 --enable-stl CC=clang-18 CXX=clang++-18
        make -j$(nproc) && sudo make install

    - name: Checkout FreePictureSplitter
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter

    - name: Build
      shell: bash
      run: |
        cd FreePictureSplitter/
        mkdir build && cd $_
        cmake .. -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-git
        path: FreePictureSplitter/build/bin
