name: macos

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest

    steps:
    # wxWidgets 
    - name: Checkout wxWidgets
      uses: actions/checkout@v4
      with:
          repository: wxWidgets/wxWidgets
          ref: v3.2.6
          submodules: recursive
          path: wxWidgets

    - name: Install a new Clang
      run: |
        #brew install llvm
        wget -q https://github.com/macports/macports-base/releases/download/v2.10.2/MacPorts-2.10.2.tar.bz2
        tar xjvf MacPorts-2.10.2.tar.bz2
        cd MacPorts-2.10.2
        ./configure && make && sudo make install
        sudo port install clang-18
        
    - name: Build and install wxWidgets
      run: |
        mkdir wxWidgets/build-release
        cd wxWidgets/build-release
        ../configure --enable-shared --disable-monolithic --with-osx_cocoa CXX='clang++ -std=c++17 -stdlib=libc++ -I../src/tiff/libtiff' CC=clang --disable-debug --disable-mediactrl --enable-stl
        make -j$(sysctl -n hw.physicalcpu)
        sudo make install

    # FreePictureSplitter
    - name: Checkout FreePictureSplitter
      uses: actions/checkout@v4
      with:
        path: FreePictureSplitter

    - name: Build FreePictureSplitter
      run: |
        cd FreePictureSplitter && mkdir build-release
        cd build-release
        brew install autoconf automake libtool gettext
        cmake ..
        cmake --build . -j $(sysctl -n hw.physicalcpu)
    
