name: Pack Packages

on:
  workflow_dispatch:
  
jobs:
  win64:
    # We create an installer on Windows.
    runs-on: windows-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.10.*
        arch: win64_msvc2022_64
        install-deps: true
        modules: "qtimageformats"
        setup-python: false
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter
        submodules: recursive
        fetch-depth: 1
      
    - name: Build
      shell: pwsh
      run: |
        cd FreePictureSplitter/
        # We do not want PCH to be enabled when building on GitHub Action
        cmake -DWITH_PCH=OFF -DCMAKE_INSTALL_PREFIX=D:\FreePictureSplitter -B build .
        cmake --build build -j --config Release
        cmake --install build --config Release
        cp -Force LICENSE D:\FreePictureSplitter\

    - name: Create an installer using Inno Setup
      shell: pwsh
      run: |
        choco install -y innosetup
        iscc /O. /FFreePictureSplitter-setup-win64 FreePictureSplitter/dist/setup-win.iss /DMyAppPath="D:\FreePictureSplitter"

    - name: Upload the installer
      uses: actions/upload-artifact@v6
      with:
        name: FreePictureSplitter-setup-win64
        path: FreePictureSplitter-setup-win64.exe
