name: Pack Full Source

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Package full source
        run: |
          TAG_NAME="${{ github.ref_name }}"
          ZIP_NAME="${TAG_NAME}-full-source.zip"
          zip -r "$ZIP_NAME" . -x "*.git*"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.ZIP_NAME }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}