name: Static Analysis

on:
  workflow_run:
    workflows: ["Test Build"]
    types:
      - completed

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.10.*
          arch: linux_gcc_64
          install-deps: true
          modules: "qtimageformats"
          setup-python: false
          
      - name: Export compile commands
        run: |
          # We do not want PCH to be enabled when building on GitHub Action
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_PCH=OFF -B build .
          
      - name: Analyze
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''  # disable clang-format checks. 
          database: ${{ github.workspace }}/build

      - name: Fail fast?!
        if: steps.linter.outputs.clang-tidy-checks-failed > 0
        run: exit 1
