name: windows-msys2

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  msys2:
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: clang64
        update: true
        install: >-
          mingw-w64-clang-x86_64-toolchain
          mingw-w64-clang-x86_64-cmake
          mingw-w64-clang-x86_64-wxwidgets3.2-common
          mingw-w64-clang-x86_64-wxwidgets3.2-msw
          make

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zxunge/FreePictureSplitter
        path: FreePictureSplitter

    - name: Build
      shell: msys2 {0}
      run: |
        cd FreePictureSplitter/
        mkdir build && cd $_
        cmake .. -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreePictureSplitter-git
        path: FreePictureSplitter/build/bin
